version: '3'

services:

  ruteando_db:
    image: postgres:latest
    env_file:
      - .env-db
    restart: always
    ports:
      - "5432:5432"

  ruteando_api:
    build:
      context: ./../
      dockerfile: docker/Dockerfile
    image: local/ruteando_api
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./../:/opt/api
    depends_on:
      - ruteando_db